name: Test and Deploy to Nightly

on:
  push:
    branches:
      - development

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Ejecutar pruebas
      - name: Run Gradle tests
        run: ./gradlew test

  deploy:
    name: Deploy to Nightly
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      # Fusionar cambios a la rama 'nightly'
      - name: Merge to nightly
        run: |
          git checkout nightly
          git merge --no-ff ${{ github.head_ref }} -m "Merge changes from development to nightly"
          git push origin nightly
