name: Test and Deploy to Nightly

on:
  push:
    branches:
      - development

jobs:
  test_linux:
    name: Run Tests (Linux)
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Configurar JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'temurin'

      # Ejecutar pruebas
      - name: Run Gradle tests
        run: ./gradlew test
  test_windows:
    name: Run Tests (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Gradle tests
        run: ./gradlew test
  deploy:
    name: Deploy to Nightly
    needs:
      - test_linux
      - test_windows
    runs-on: ubuntu-latest
    if: success()

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      # Configurar Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Get data
        run: git fetch --all

      # Fusionar cambios a la rama 'nightly'
      - name: Checkout to nightly
        run: git checkout nightly

      - name: Merge it
        run: git merge --no-ff ${{ github.head_ref }} -m "Merge changes from development to nightly" --allow-unrelated-histories --strategy-option theirs development

      - name: Push branch
        run: git push origin nightly
